### ISSUE TITLE
objects.CommonPrefixes

### ISSUE THREAD

**Issue by Lochemage** [jamhall/s3rver#10]
This is part of the object structure retrieved by `listObjects()`, similar to `objects.Contents`, which lists out all keys that match between the `prefix` and the `delimiter`. Note, this value only exists if a delimiter is used.

The definition for the `CommonPrefixes` property is:
**Gets the CommonPrefixes property. A response can contain CommonPrefixes only if you specify a delimiter. When you do, CommonPrefixes contains all (if there are any) keys between Prefix and the next occurrence of the string specified by delimiter. In effect, CommonPrefixes lists keys that act like subdirectories in the directory specified by Prefix. For example, if prefix is notes/ and delimiter is a slash (/), in notes/summer/july, the common prefix is notes/summer/.**

Source: http://docs.aws.amazon.com/sdkfornet1/latest/apidocs/html/T_Amazon_S3_Model_ListObjectsResponse.htm

This issue relies on issue #9 to support delimiters.

**Comment by jamhall** [comment]
Thanks!

**Comment by Lochemage** [comment]
Works now!
