### ISSUE TITLE
Support NextMarker for listObjects and NextContinuationToken for listObjectsV2

### ISSUE THREAD

**Issue by leontastic** [jamhall/s3rver#110]
We currently don't return NextMarker in truncated List Object V1 responses: https://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketGET.html

Nor do we return NextContinuationTokens in truncated List Object V2 responses: https://docs.aws.amazon.com/AmazonS3/latest/API/v2-RESTBucketGET.html

Would be great to support these so users can write integration tests for cases where >1000 objects exist in a bucket.

**Comment by kherock** [comment]
I'm almost done with this, currently trying to RE continuation token generation for fun. I don't have any solid leads, but so far I've discovered
* the base64-encoded token always begins with `1`
  * furthermore, the first 8 bytes as a UInt32BE tend to exist within the 3560000000-3620000000 range
* the length of the token can vary greatly and is correlated with the length of the key (with the bucket name, and potentially region)
* the length of the token increases in 7-9 byte increments for every 8 characters in the key name - from my brief experimentation:

| Key | Key Length | Token Length |
| ---- | ------------ | --------------- |
`us-east-1/<04-char bucket name>/a` | 16 | 24 bytes
`us-east-1/<04-char bucket name>/abcdefgh` | 23 | 24 bytes
`us-east-1/<04-char bucket name>/abcdefgh` `i` | 24 | 33 bytes (+9)
`us-east-1/<04-char bucket name>/abcdefgh` `ijklmnop` | 31 | 33 bytes
`us-east-1/<04-char bucket name>/abcdefgh` `ijklmnop` `q` | 32 | 41 bytes (+8)
`us-east-1/<04-char bucket name>/abcdefgh` `ijklmnop` `qrstuvwx` | 39 | 41 bytes
| | |
`us-east-1/<26-char bucket name>/a` | 38 | 41 bytes
`us-east-1/<26-char bucket name>/ab` | 39 | 41 bytes
`us-east-1/<26-char bucket name>/ab` `c` | 40 | 48 bytes (+7)
`us-east-1/<26-char bucket name>/ab` `cdefghij` `k` | 49 | 57 bytes (+9)
`us-east-1/<26-char bucket name>/ab` `cdefghij` `klmnopqr` `s` | 57 | 65 bytes (+8)
`us-east-1/<26-char bucket name>/ab` `cdefghij` `klmnopqr` `stuvwxyz` `0` | 64 | 72 bytes (+7)

From this, my best guess is that the first 8 bytes form either the IV of a streaming cipher or the key used to derive a symmetric encryption key. That leaves the remaining bytes as the either ciphertext or XOR'd result of the key name given illustrated by the table above.
