### ISSUE TITLE
Index document, Error document, and CORS config should all be per-bucket options

### ISSUE THREAD

**Issue by kherock** [jamhall/s3rver#115]
Normally they must be manually enabled/set after creating each bucket in the S3 console. This can cause problems if you want to have one bucket doing static web hosting and another for normal storage/retrieval.

If we also get around to implementing versioning it's also important that it can be enabled per-bucket.

**Comment by specialkk** [comment]
For convenience I think it wouldn't be bad to leave the current server-wide options in and use them when creating new buckets. I'm thinking the best way would be a simple key-value `.cfg` file for every bucket created stored in the top level of the data directory. It would make changing these options pretty simple and straightforward as long as it's documented.
