### ISSUE TITLE
Use prettier

### ISSUE THREAD

**Issue by n1ru4l** [jamhall/s3rver#119]
There are many reformats in the last pull requests.
If we use a code format tool like prettier we could prevent that.

What do you think? I could make a pull request for this.

**Comment by specialkk** [comment]
I definitely support using eslint with a pre-commit hook at a minimum. I haven't dealt with prettier, it seems a little intense.

If you want to do prettier instead I'd probably be okay with whatever (sensible) rules you choose.

**Comment by leontastic** [comment]
Pre-commit with prettier would be pretty good

Could also add a linting step to the CI

**Comment by n1ru4l** [comment]
We can use https://github.com/hexacta/prettier-check for checking the style in CI.

Do you all agree witch switching to eslint?

**Comment by leontastic** [comment]
I'm OK with eslint or prettier, just wondering @n1ru4l if you intend to extend prettier rules. If not then we can just use prettier directly. I would prefer to adopt a widely used ruleset with _strictly_ no additional opinion (prettier, airbnb, standard, etc). I don't want to see contributors discussing styling preferences frequently, it takes away focus on real issues.

**Comment by n1ru4l** [comment]
@leontastic I would say we use the default prettier config. With https://github.com/prettier/eslint-config-prettier to disable all eslint rules that conflict with prettier.

I am not sure about the eslint config.. `eslint:recommended` might be enough.

**Comment by specialkk** [comment]
I guess what I'm not getting is why we need `eslint` at all if `prettier` can be run directly. Is it just for IDE integration?

**Comment by n1ru4l** [comment]
Because prettier is about code formatting and eslint is more about linting e.g. no unused declarations.
We could also continue using jshint but I do not want to spend my time disabling every rule that conflicts with prettier 😅

**Comment by leontastic** [comment]
Doing more reading into it I think @n1ru4l is right – it would be prudent to use both, eslint for enforcing consistent syntax and prettier for consistent formatting.

I'm a big fan of [standard](https://github.com/standard/eslint-config-standard). But I don't have a strong opinion since this is an open-source repo anyway – we can start with `eslint:recommended` for simplicity if we don't all have the same preferences.

**Comment by specialkk** [comment]
grrr standard. I'm fine with just `eslint:recommended`.
