### ISSUE TITLE
move cors_sample_policy.xml out of test/

### ISSUE THREAD

**Issue by mvayngrib** [jamhall/s3rver#123]
thanks for the module guys!

`lib/index.js` requires this file. Some preprocessing modules delete the test/ folder as it's not expected to be needed in production (e.g. https://github.com/tj/node-prune)

**Comment by specialkk** [comment]
Well it's not expected that this project is to be used in production 😛.

We were expecting something like this could potentially happen, I can fix this in a bit.

**Comment by mvayngrib** [comment]
haha, you're right about production, didn't think about it :) Thanks anyway for removing it.
