### ISSUE TITLE
Delimiter stripped from paths

### ISSUE THREAD

**Issue by jwest-rms** [jamhall/s3rver#21]
It looks like there is a small difference between s3rver's handling of delimiter parameters.  In the AWS response, each Prefix in CommonPrefixes includes the trailing delimiter, but s3rver strips it off. I believe this [line](https://github.com/jamhall/s3rver/blob/master/lib/file-store.js#L117) should be 
`match = match.substr(0, delimiterIndex + 1);`

**Comment by jamhall** [comment]
Hello @jwest-rms . Thank you for the report. I will look into it tomorrow :)

**Comment by jamhall** [comment]
Hello @jwest-rms. Apologies for the delay.

This should now be rectified. Please confirm if this works for you. (I haven't push to NPM yet)
