### ISSUE TITLE
copyObject fail if src = dest

### ISSUE THREAD

**Issue by RonanDrouglazet** [jamhall/s3rver#22]
If we just want to update metadata, we normally can call a copyObject with the src = dest and just update metadata 

but this fail here 
https://github.com/jamhall/s3rver/blob/master/lib/file-store.js#L277 (from node-fs-extra i think)

maybe it's ok to check if src = dest and so just update metadata without copying etc.. ?

**Comment by jamhall** [comment]
Hi @RonanDrouglazet . I have pushed a fix to master. Please confirm if this works for you! I have also implemented a test for this situation.

**Comment by RonanDrouglazet** [comment]
Thanks a lot @jamhall !! It's perfect ! 

Very helpfull project, thanks for it !

**Comment by jamhall** [comment]
Excellent! You're welcome!
