### ISSUE TITLE
Creating Error in S3 putObject

### ISSUE THREAD

**Issue by mjabraham47** [jamhall/s3rver#231]
Is it possible to use this library to mock out an s3 and cause an error to occur while uploading? Ideally I'd like to be able to successfully pass a few files with putObject and then have some of them 'error'

**Comment by specialkk** [comment]
Ooh, that's in an interesting idea, though I think that kind of responsibility should fall on whatever testing framework you're using. I believe you might already be able to accomplish some of what you want with [`nock`](https://github.com/node-nock/nock).

Is there any specific interface you had in mind for setting up requests that should fail?

**Comment by mjabraham47** [comment]
I suppose the most useful thing would be some kind of additional parameter to determine if (a) all the requests should fail or (b) a random number of the requests should fail or (c) half the requests should fail.

Thanks for recommending [nock](https://github.com/node-nock/nock), it looks like it might be helpful
