### ISSUE TITLE
XMLParserError: Non-whitespace before first tag

### ISSUE THREAD

**Issue by pscanf** [jamhall/s3rver#24]
Creating a bucket using the `aws-sdk-js` client produces the following error:

```
XMLParserError: Non-whitespace before first tag.
Line: 0
Column: 1
Char: C
```

`s3rver` logs:

```
info: PUT / 404 13 - 4.628 ms
```

`fake-s3` works fine though, so I thought it might be a problem with `s3rver`.
FYI, running code in node `v5.3.0`.

**Comment by jamhall** [comment]
Hi there.

What's the code you're executing using aws-sdk-js? Trying to create bucket?

It's normal it is returning 404 as there is no PUT route mapped to '/'. Maybe the aws-sdk expects an XML response when a 404 is thrown?

Does fake-s3 return XML? if so, could you give me the XML it's returning?

Thank you!

**Comment by pscanf** [comment]
Hi @jamhall, thanks for the quick response. :-)

I set up a repo reproducing the "bug" (though it might just a misuse on my end :-) ).

https://github.com/pscanf/s3rver-bug-reproduction

**Comment by joshwils82** [comment]
Hi @jamhall, has there been any update on this?  I am running into the same problem with aws-sdk 2.3.3 in node.

**Comment by leontastic** [comment]
@pscanf I took a look at your project reproducing your issue. I was able to resolve your issue by adding `s3ForcePathStyle: true` to the S3 config object (we do this in [the tests](https://github.com/jamhall/s3rver/blob/master/test/test.js#L37)).
