### ISSUE TITLE
Write protection

### ISSUE THREAD

**Issue by eMerzh** [jamhall/s3rver#26]
I know it's probably not the plan of the tool, 

but i wanted to know if i have a possibility to set like a tiny security thing to avoid everyone writing on it... (reading shouldn't be a problem)

Thanks for your tool

**Comment by jamhall** [comment]
Hi @eMerzh !

Unfortunately, no there is no plan to implement this. f you wish to implement this, then that would be awesome and I would be very happy to accept a pull request :)

Thank you!
