### ISSUE TITLE
Callback to instance.close() not optional anymore

### ISSUE THREAD

**Issue by rocketeric** [jamhall/s3rver#269]
Using `s3rver v2.2.4`
Using `@types/s3rver v0.0.30`

We recently upgraded from s3rver v2.0.1 to v2.2.4 and started getting errors saying `callback is not a function` from s3rver lib/index.js:61 in our test clean up methods when closing down the s3rver instance. 

In the previous s3rver version, the callback passed to the `instance.close()` method was optional. Now, looking at lib/index.js, the callback is clearly not optional anymore, despite the typescript types package claiming it is. 

Our workaround for now is to pass `() => {}` into `instance.close()`. 

Please make the callback optional like it was in the previous version.

**Comment by leontastic** [comment]
@rocketeric Published v2.2.5 with the fix for this issue. Thank you for the bug report.
