### ISSUE TITLE
putObject is always a folder

### ISSUE THREAD

**Issue by coulonxyz** [jamhall/s3rver#274]
Hi,

I'm trying to put a file on my fake S3 bucket, and it always appear as a folder and not a file. 

my function to put:

    function putFile(s3: S3, sourceFolder: string, sourceFileName) {
          return new Promise((resolve) => {
           fs.readFile(sourceFolder + '/' + sourceFileName, function(err, data) {
              if (err) {
                throw err;
              }
          
              s3.putObject({
                Bucket: config.aws.s3.bucketName,
                Body: new Buffer('abcd'),
               Key: 'myKey',
              }, function() {
                resolve()
              });
            });
          });
        }

The result:
drwxrwxr-x 2 name name4096 juil.  4 18:21 myKey

I'm running version 2.2.4.

is this a known issue ?

Julien

**Comment by specialkk** [comment]
It looks like it's working as expected. The data folder isn't meant to be explored, it's just for s3rver's implementation of storing and retrieving objects with their metadata. Each object is stored as a content file and metadata file within a folder matching the key name you've specified.

If you want a way to explore a bucket you can either use the aws cli or something like s3fs if your on Linux.

**Comment by coulonxyz** [comment]
ok, thanks for the clarification. I wanted to pull a gz file a gunzip it to test my solution end-to-end but I guess i will have to figure out something else.
Thanks a lot.
