### ISSUE TITLE
Problem with Using s3fs-fuse with S3rver

### ISSUE THREAD

**Issue by Lsardi** [jamhall/s3rver#293]
Hi,
i have a projet who use S3 bucket and i want to test it.
when i launch this command  

> s3fs bucket1 /tmp/3 -o url="http://localhost:4568" -o use_path_request_style -d -f -o f2 -o curldbg

i have this response

> s3fs: could not determine how to establish security credentials.

Can you help me please ?

**Comment by specialkk** [comment]
s3fs requires a set of credentials to be provided even though S3rver doesn't care about any credentials provided. So you just need to provide a dummy credential file for s3fs to use.

**Comment by Lsardi** [comment]
Thanks you for your response, can you give me a example of credentials files please ?

**Comment by nmstoker** [comment]
@Lsardi As you're asking about another project, I suspect you'd do better trying to resolve that by looking at https://github.com/s3fs-fuse/s3fs-fuse/blob/master/README.md#examples

**Comment by kherock** [comment]
The link above has what you need, closing this.
