### ISSUE TITLE
PUT large object doesn't create custom metadata

### ISSUE THREAD

**Issue by whereandy** [jamhall/s3rver#306]
When I create large objects, the metadata doesn't seem to be created. For example, a 12mb file I transfer to a S3rver instance creates a `.dummys3_metadata` whose contents are `{"contentType":"binary/octet-stream","customMetaData":[]}`. 

Have you observed this issue before?

**Comment by kherock** [comment]
I can't reproduce this, I think I need a solid example. The test case for custom metadata still succeeds when I modified to put a 12mb buffer instead?

**Comment by leontastic** [comment]
@whereandy We can probably address this issue fastest if you provide us a small repository with the minimal amount of code and assets needed to reproduce the issue.
