### ISSUE TITLE
Does this project actually serve files off the filesystem?

### ISSUE THREAD

**Issue by SeanHayes** [jamhall/s3rver#32]
Or is it the same deal as this? https://github.com/jubos/fake-s3/issues/30

When I load the root directory I get a list of folder names as buckets, but visiting any of those buckets gives me:
http://localhost:5353/media/
```
<ListBucketResult xmlns="http://doc.s3.amazonaws.com/2006-03-01">
<Prefix/>
<Marker/>
<MaxKeys>1000</MaxKeys>
<IsTruncated>false</IsTruncated>
</ListBucketResult>
```

**Comment by jamhall** [comment]
hi @SeanHayes. Thanks for your question. Unfortunately with s3rver (like s3), you can't point it to an arbitrary directory and expect it to return a list of objects (files). Each object in s3rver has a `.dummys3_content` to store the content and a `.dummys3_metadata` to store it's relevant metadata.
An example of metadata:
```
{  
   "md5":"a15ce283ead93d68c1b87d0bafed1523",
   "contentType":"application/octet-stream",
   "size":52352,
   "modifiedDate":"2016-02-25T11:28:09.000Z",
   "creationDate":"2016-02-25T11:28:09.000Z",
   "customMetaData":[  
      {  
         "key":"x-amz-meta-somekey",
         "value":"value"
      }
   ]
}
```

Hope this answers your question!

**Comment by ajxs** [comment]
For most applications using S3, the intended result of uploading a file to S3 is having a file statically hosted, which can be retrieved by it's URL. I just set this up for my project under the assumption that it would provide this functionality, and unfortunately I'll have to opt for another solution! Are there any plans to offer similar file serving in the future?

**Comment by specialkk** [comment]
@ajxs I wouldn't recommend reviving a zombie thread if you want some in depth discussion on this.

To answer your question, s3rver works as a local drop-in replacement for an actual S3 endpoint, so uploading a file to S3 would make it accessible via a URL comprising the bucket name and key. There aren't plans for supporting what this issue asks as it would sacrifice a lot of accuracy that isn't possible to keep within the structure of a normal directory tree.

However, you could use `s3fs` if you just want to quickly upload an entire directory tree to a local s3rver instance.
