### ISSUE TITLE
Range handling broken for out-of-bounds and too-large requests

### ISSUE THREAD

**Issue by jnardone** [jamhall/s3rver#374]
Range requests are failing in two notable ways:

1) any range that can't be serviced must return a 416, but s3rver is returning a 206
2) the content served should indicate the actual size of returned data vs. the requested size.  If a range of 500-1000 is requested, but the file ends after 600 bytes, s3rver should return a length of 100, not 500.

PR for this is here: https://github.com/jamhall/s3rver/pull/373.  This fixes issues that were preventing us from using this with https://github.com/jb55/s3-blob-store among other libs.

**Comment by leontastic** [comment]
Fixed in #373
