### ISSUE TITLE
Header Options

### ISSUE THREAD

**Issue by BenSower** [jamhall/s3rver#38]
Heyho, is it planned to add more options (e.g. header options like 'cache-control', as for example defined here: http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#copyObject-property) to the aws-functions as well as the according controllers?

I am manually setting the 'Cache-control' option on a couple of objects and would like to be able to test for the correct response. 

Thanks for your time and good work!

**Comment by jamhall** [comment]
Hi @BenSower ! There is currently no plan to implement this. I should/might have some time this week to have a look at this.

Thanks

**Comment by BenSower** [comment]
xD That ticket was so old that I forgot it even existed. Admit it: you didn't want it to be older than two years :-P!
