### ISSUE TITLE
Delete bucket fails after deleting all objects in the bucket

### ISSUE THREAD

**Issue by joshwils82** [jamhall/s3rver#39]
If I create a bucket "test" and add the following object keys:

index.html
styles/main.css

Then if I delete all the objects and try to delete the bucket I get the following error:

Unable to delete bucket test:  {
  "message": "The bucket your tried to delete is not empty",
  "code": "BucketNotEmpty",
  "region": null,
  "time": "2016-04-18T19:27:26.649Z",
  "requestId": null,
  "extendedRequestId": null,
  "statusCode": 409,
  "retryable": false,
  "retryDelay": 0.46673882752656937
}

However, the bucket is empty if I view it through the browser.

The problem appears to be that the "styles" directory is still present in the data dir even though all keys have been deleted.

If I manually delete the styles directory, then I am able to delete the bucket.  So there appears to be an issue cleaning up empty directories once all keys have been deleted.

**Comment by jamhall** [comment]
Hello @joshwils82 - Thank you for reporting this. Do you think you could make a pull request? If not, I should have some time this week to get around to this and the various other outstanding issues. 

Thank you!

**Comment by joshwils82** [comment]
Hi @jamhall, 

I might be able to find some time to put together a pull request. I will try to pull something together over the next couple of days.  Otherwise, if you get to it first just let me know.

Thanks!

**Comment by n1ru4l** [comment]
There is actually no such concept as directories on S3. It is only key/value.
Therefore folders should be deleted once they are empty.
