### ISSUE TITLE
code question: where is HEAD managed ?

### ISSUE THREAD

**Issue by allanlegalstart** [jamhall/s3rver#425]
I'm trying to use the master branch to have a fake s3 for my django code, however it fails because the `python manage.py collectstatic` tries to do some `HEAD` request on objects , and it fails with a `403`.

However the  `.head()` method is not implemented in router.js 

so I'm a bit clueless on where is it handled 

(on the other side it seems to be handle for buckets url)

**Comment by kherock** [comment]
HEAD is implicitly handled by the .get() handlers in `koa-router` (I think Express's router behaves the same way). If you can share the specific AWS error code I can probably provide more insight.
