### ISSUE TITLE
Implement Upload Part - Copy

### ISSUE THREAD

**Issue by juliangruber** [jamhall/s3rver#436]
The response body of `s3.uploadPartCopy` should contain `{ CopyPartResult: { ETag, ... } }`, however I'm just receiving `{ CopyPartResult: {} }`.

See https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#uploadPartCopy-property.

**Comment by kherock** [comment]
[Upload Part - Copy](https://docs.aws.amazon.com/AmazonS3/latest/API/mpUploadUploadPartCopy.html) isn't actually supported by S3rver, but I can at least have that stubbed with 501 error for the next patch release so that the behavior isn't as confusing.

**Comment by kherock** [comment]
It doesn't look too difficult to add though, I'll try to address this for v3.1 (PRs are welcome)!

**Comment by juliangruber** [comment]
Draft PR here, I'm continuing to work on this: https://github.com/jamhall/s3rver/pull/443

**Comment by kherock** [comment]
The support that was implemented by #443 has been merged into `main` and will be available in the first 4.x release.
