### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present in ListAllMyBucketsResult packet

### ISSUE THREAD

**Issue by feuGeneA** [jamhall/s3rver#449]
I'm successfully configuring CORS on a bucket level, but I have an application that wants to do a `GET /`, aka a ListBuckets request, and I need the ACAO header to be in the response, but it's not:

![image](https://user-images.githubusercontent.com/7883777/56693211-d88eea00-66b1-11e9-8585-4c4b279036c9.png)

For comparison (that is, for proof that CORS is working on the bucket level), here's a view of a listing for a specific bucket:

![image](https://user-images.githubusercontent.com/7883777/56693405-5c48d680-66b2-11e9-9623-a16fe0c949ff.png)

Here's how I'm starting my server:

```TypeScript
    await new S3rver({
        port: argv.port,
        address: 'localhost',
        silent: false,
        cors: fs.readFileSync(require.resolve('s3rver/example/cors.xml')),
        directory: argv.directory,
        configureBuckets: [
            { name: 'doc-jsons', configs: [fs.readFileSync(require.resolve('s3rver/example/cors.xml'))] },
            { name: 'staging-doc-jsons', configs: [fs.readFileSync(require.resolve('s3rver/example/cors.xml'))] },
        ],
    }).run();
```

I don't know where I got that `cors:` setting from, but it doesn't seem to do anything...

Is there a way to configure non-bucket-level CORS support?

**Comment by kherock** [comment]
That option was from S3rver 2.x - I have no idea what S3's ListBuckets CORs behavior is other than that it's probably not configurable. It should be easily fixable though.

I can take a look at this and your #448 later tonight. Thanks for reporting these!

**Comment by kherock** [comment]
Have you been able to verify that you can perform this request against the real S3 endpoint? From my own testing and some [quick](https://stackoverflow.com/questions/35004258/cors-error-with-listbuckets-in-aws-js-sdk) [googling](https://github.com/aws/aws-sdk-js/issues/1939) it doesn't look like the service-level endpoints support CORS.

**Comment by kherock** [comment]
Closing as invalid.
