### ISSUE TITLE
Include type definitions in library

### ISSUE THREAD

**Issue by jpike88** [jamhall/s3rver#461]
Prefer not to use @types/s3rver for such a small file... can you include it in this library? Also, they're out of date (missing the middleware function)

**Comment by kherock** [comment]
I agree that the typings currently in DefinitelyTyped's repo are very dated; almost everything about that file is wrong.

This project doesn't really benefit from being native TS, and I'm not a fan of maintaining a separate type definition file. Though I can see about making the existing JSDoc comply with [TypeScript's support for extracting types from JSDoc annotations](https://github.com/Microsoft/TypeScript/wiki/JSDoc-support-in-JavaScript).

**Comment by jpike88** [comment]
If I fashioned up an up-to-date definition file, would you accept it? I have countless libraries, and they all sit well in TS apart from this one... it's detrimental to have an @types definition that clashes with your library. The s3rver api isn't particularly complex?

**Comment by jpike88** [comment]
closing for now unless you want me to do it
