### ISSUE TITLE
MAJOR ISSUE: callback() does not execute configureBuckets property

### ISSUE THREAD

**Issue by jpike88** [jamhall/s3rver#463]
I have to run() the server first to initialise buckets and cors before I can insert it as a middleware.

Can the initialization of buckets etc take place when callback() is made?

to clarify:

```
(new S3rver({
		silent: !core.config.verboseLogs,
		directory: awsDir,
		configureBuckets: [{
			name: aws.filesBucket,
			configs: [`
			<CORSConfiguration>
				<CORSRule>
					<AllowedOrigin>*</AllowedOrigin>
					<AllowedMethod>GET</AllowedMethod>
					<AllowedMethod>POST</AllowedMethod>
					<MaxAgeSeconds>3000</MaxAgeSeconds>
					<AllowedHeader>Authorization</AllowedHeader>
				</CORSRule>
			</CORSConfiguration>
			`]
		}]
	}) as any).callback()
```

configureBuckets never gets looked at in the above code when it should have been.

**Comment by jpike88** [comment]
Current workaround:

```
(async () => {
		await s3rverInstance.run();
		await s3rverInstance.close();
	})();

	const s3rverMiddleware = s3rverInstance.callback();
	app.use('/upload', (req, res, next) => {
		req.url = req.originalUrl;
		s3rverMiddleware(req, res, next);
	});
```

**Comment by kherock** [comment]
I think exposing a new method for updating configs should solve this. I can't make `.callback()` return a Promise.

**Comment by jpike88** [comment]
shouldn't callback() fire the logic that happens in run(), if the server isn't currently in 'run' mode? Bucket initialisation should be something done whether you're calling run or not right? I'm only calling run right now because that's the only way to init the buckets
