### ISSUE TITLE
Is it possible to add support for post object action ?

### ISSUE THREAD

**Issue by swiftanthony** [jamhall/s3rver#47]
I mean can this action be added to s3rver. It is very similar putOblect:
`app.post('/:bucket/:key(*)', controllers.bucketExists, controllers.postObject)`

**Comment by jamhall** [comment]
Hello @swiftanthony 

According to the [documentation](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPOST.html):

> The POST operation adds an object to a specified bucket using HTML forms. POST is an alternate form of PUT that enables browser-based uploads as a way of putting objects in buckets. Parameters that are passed to PUT via HTTP Headers are instead passed as form fields to POST in the multipart/form-data encoded message body. 

Feel free to implement multi-part uploads and send a pull request :) Alas, I don't have much time at the moment to implement it. There is another issue that wants this feature: https://github.com/jamhall/s3rver/issues/33

**Comment by swiftanthony** [comment]
Thanks @jamhall 
I don't have much time at present myself, but I will look into this one once I get a bit of breathing space.
