### ISSUE TITLE
When using the AWS Java SDK to put an object, I get ClientException

### ISSUE THREAD

**Issue by StefH** [jamhall/s3rver#48]
> Exception in thread "main" com.amazonaws.AmazonClientException: Unable to verify integrity of data upload.  Client calculated content hash (contentMD5: Jm1/xmb+
> /xtOXxs3kouTwg== in base 64) didn't match hash (etag: 67c2ab887738c99b76097e94e2c46293 in hex) calculated by Amazon S3.  You may need to delete the data stored
> in Amazon S3. (metadata.contentMD5: null, md5DigestStream: com.amazonaws.services.s3.internal.MD5DigestCalculatingInputStream@b672aa8, bucketName: hello-world, key: hello-world/file_636120414036520000.txt)
>         at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1611)
>         at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:3149)
>         at xxx.common.aws.s3.S3Context.putObjectAsString(S3Context.java:26)
>         at xxx.hello.MainService.Put(MainService.java:23)
>         at xxx.hello.HelloWorldApplication.main(HelloWorldApplication.java:17)

Any clue?

**Comment by j-kidd** [comment]
I know this is old but I'm having this issue using the latest AWS Java SDK (1.11.86).

It looks like this issue was raised over on 'fake-s3' too [https://github.com/jubos/fake-s3/issues/164](https://github.com/jubos/fake-s3/issues/164), and that it's an issue with the switch to chunked encoding. Any chance this might be supported?

**Comment by grofit** [comment]
I get a very similar issue but am using the .net awssdk, where doing `PutObjectAsync` constantly fails the hash part, the use case looks like:

```
public async Task PersistDocument(Guid documentId, byte[] documentdata)
        {
            using (var stream = new MemoryStream(documentdata))
            {
                var request = new PutObjectRequest
                {
                    BucketName = _bucketName,
                    Key = documentId.ToString(),
                    InputStream = stream,
                    AutoResetStreamPosition = true
                };

                await _s3.PutObjectAsync(request);
            }
        }
```

**Comment by grofit** [comment]
I have even just tried something simple like:

```
var request = new PutObjectRequest
{
	BucketName = _bucketName,
	Key = documentId.ToString(),
	ContentBody = "test data"
};

_s3.PutObject(request);
```

This also just raises the hash error, tried setting content length and other things but it just seems like any call to that with the .net client just dies, although I can see it did the put in the s3rver output:

```
info: [S3rver] Stored object "2ecc8afc-9ea5-4eec-9043-fdfe97e0a229" in bucket "some-bucket" successfully
info: [S3rver] PUT /filestore-qa/2ecc8afc-9ea5-4eec-9043-fdfe97e0a229 200 - - 25.658 ms
```

**Comment by TimJRodgers** [comment]
grofit, try setting SignatureVersion ="2" in AmazonS3Config when initializing the client.

**Comment by grofit** [comment]
Hey, thanks for getting back to me, my issue specifically was that I was using credentials when I should have just left them empty.

**Comment by leontastic** [comment]
Closing due to staleness. I can reopen if someone else encounters this.
