### ISSUE TITLE
Calling HEAD on an empty file will return an error

### ISSUE THREAD

**Issue by ksnll** [jamhall/s3rver#484]
When trying to put an empty file, `content` [here](https://github.com/jamhall/s3rver/blob/be12af82f09a1028f2e4b2604a746561960d33ab/lib/controllers/object.js#L194) will be `null` and will fail with `Cannot read property 'destroy' of null`
Current s3 behaviour is to handle the empty file correctly

**Comment by kherock** [comment]
I'm not able to reproduce making `object.content` `null` when putting an empty file. Within S3rver I'm seeing an empty stream, and when retrieving the object via the Node.js aws-sdk it correctly gives an empty Buffer. The following test I attempted works just fine:

```javascript
  it("should store an empty object in a bucket", async function() {
    await s3Client
      .putObject({
        Bucket: buckets[0].name,
        Key: "somekey",
        Body: fs.createReadStream('./empty')
      })
      .promise();
    const object = await s3Client
      .getObject({ Bucket: buckets[0].name, Key: "somekey" })
      .promise();
    expect(object.ETag).to.match(/"[a-fA-F0-9]{32}"/);
  });
```
where "empty" is a zero-byte file.

**Comment by ksnll** [comment]
Thanks for having a look 👍 
I think it's getting triggered only by the [`HEAD` method](https://github.com/jamhall/s3rver/blob/be12af82f09a1028f2e4b2604a746561960d33ab/lib/controllers/object.js#L193) after the object has been `PUT`
If you need more context let me know

**Comment by kherock** [comment]
I was able reproduce this by modifying that test to use HEAD instead, so thanks for the suggestion. It was a subtle bug but fortunately had a simple fix. I think I should finally have some time to put together a release tonight, thanks for your patience.
