### ISSUE TITLE
fast-xml-parser breaking change with tagValueProccessor

### ISSUE THREAD

**Issue by jagregory** [jamhall/s3rver#497]
fast-xml-parser have pushed a new version with breaking changes (in a patch release...). See: https://github.com/NaturalIntelligence/fast-xml-parser/issues/178

As the version in the package.json is `^3.12.13`, anyone doing a fresh install will get the offending `3.12.19` version.

The change stops coercing tag values to strings for tagValueProcessor, so the call to `he.encode` fails.

Fixes:

  - Pin the dependency to `3.12.18`, or
  - Update tagValueProcessor to only call `he` when the value is a string.

**Comment by Ankcorn** [comment]
I have made a pull request https://github.com/jamhall/s3rver/pull/496 that fixes the issue by naively   combining the callback param for tagValuePorcessor with a string.

I think we need to find a way to poke the maintainer so they can fix this.

**Comment by kherock** [comment]
This is now fixed in v3.3.0. @Ankcorn, sorry I didn't end up accepting your PR - there were a couple minor adjustments that I wanted, and I ended up reimplementing the workaround myself. Regardless, thanks for bringing this to my attention!

**Comment by Ankcorn** [comment]
Thanks @kherock 👍 I really appreciate your work on this.
