### ISSUE TITLE
/usr/bin/env: 'node\r': No such file or directory

### ISSUE THREAD

**Issue by pitrou** [jamhall/s3rver#508]
I've just installed s3rver on Ubuntu 18.04 with the following:
```
sudo npm install s3rver -g
```
But when I try to launch it I get the following error:
```
$ s3rver 
/usr/bin/env: «node\r»: Aucun fichier ou dossier de ce type
$ LANG=C s3rver 
/usr/bin/env: 'node\r': No such file or directory
```

It seems `/usr/local/bin/s3rver` uses Windows newlines (`\r\n`) and `/usr/bin/env` doesn't like this.

**Comment by kherock** [comment]
Can you check if this is still a problem in v3.4.0?

**Comment by pitrou** [comment]
Seems to work, thank you!
