### ISSUE TITLE
Support Signature Version 4 streaming API

### ISSUE THREAD

**Issue by ad-m** [jamhall/s3rver#534]
Hello,

I would like notice that all AWS migrated to signature v4. It mean some client eg. Restic no longer able to s3rver. In case of signed chunked data ( https://docs.aws.amazon.com/en_pv/AmazonS3/latest/API/sigv4-streaming#sigv4-chunked-upload-sig-calculation-chunk0 ) saved data is corrupted. 

Here is implementation of Signature v4 in NodeJS which can be inspiring:

- https://github.com/noobaa/noobaa-core/commit/6c95ba38b958d32e24493a4a589abfe630aa6056 (I tested that stream transform and it correctly drop signatures from stream)
- https://github.com/scality/cloudserver/blob/9615d51c9e0500db37905dcfd04b17187132eddf/lib/auth/streamingV4/V4Transform.js

Greetings,

**Comment by sgillespie** [comment]
This is indeed breaking the Java SDK v2, and results in the following error on `putObject`:

```
Exception in thread "main" software.amazon.awssdk.core.exception.SdkClientException: Data read has a different checksum than expected. Was 0xaaf62ecf2a67b8cc3d05b40f04ddb4ff, but expected 0xc
964993c6bbd449be0bca24e4747c053                                                                                                                                                                
        at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:98)                                                                              
        <-- Snip -->
        at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:55)
        at software.amazon.awssdk.services.s3.DefaultS3Client.putObject(DefaultS3Client.java:7119)
```

The workaround I have found is to disable this entirely (syntax in Kotlin):

```
val config = AwsRequestOverrideConfiguration.builder().signer(NoOpSigner()).build()
val req = PutObjectRequest
            .builder()
            .overrideConfiguration(config)
            // other options
            .build()
```

I'd be happy to put together a PR if I can find the time

**Comment by kherock** [comment]
Signature Version 4 support is planned for the next major release, so stay tuned over the next few weeks for that.

However, I haven't really investigated chunked uploads so it might take some time to support them adequately. @ad-m thanks for the reference links!

@sgillespie are the snippets you pasted using `EventStreamAws4Signer`? Let me know if you still have issues using `AwsS3V4Signer`. - I'm just looking for confirmation that you're experiencing the same issue.

**Comment by sgillespie** [comment]
That's from whatever was default on `S3Client`, `AwsS3V4Signer` I think?

**Comment by kherock** [comment]
I'm not familiar with the Java SDK, I was wondering if you were able to tell. Plain V4 signed requests shouldn't be corrupting data, but chunked requests might have more severe issues.
