### ISSUE TITLE
Doesn't seem to show files when using `ls` command from aws-cli

### ISSUE THREAD

**Issue by justinmchase** [jamhall/s3rver#55]
I made a folder with some sub folders and files but none of my files seem to show up when I use the aws-cli. I am on osx, running the s3rver programmatically from within gulp.

I have a dir structure like:
```
integration
  /testbucket1
    - example.txt
  /testbucket2
    - example2.txt
```

But when I run this:
```
$ aws s3 ls s3:// --endpoint http://localhost:4569 --recursive
2017-02-21 15:29:54 testbucket1
2017-02-22 09:46:10 testbucket2
```

The files are not being picked up by recursive. Also if I `ls` into a specific bucket I get no files:
```
$ aws s3 ls s3://testbucket1 --endpoint http://localhost:4569 --recursive
```

Output from s3rver from above commands:
```
[09:52:26] Starting 'startServer'...
info: Fetched 2 buckets
info: GET / 200 478 - 10.822 ms
info: Fetched bucket "testbucket1" with options [object Object]
info: Found 0 objects for bucket "testbucket1"
info: GET /testbucket1 200 222 - 2.326 ms
```

No results. What am I doing wrong? Why isn't it finding files as objects?

What I want to do is to use this to just serve up some local files for integration testing purposes and just configure the endpoint to point locally. Any help would be appreciated here.

**Comment by jamhall** [comment]
@justinmchase  - Hello! 

I've just tested in on my machine:
```bash
aws s3 ls s3://bucket1 --endpoint http://localhost:4568 --recursive

2017-02-22 17:07:51      92629 jquery
2017-02-22 17:07:52   20000000 large
2017-02-22 17:07:53          6 multi/directory/path/text
2017-02-22 17:07:51          6 text
2017-02-22 17:07:51          6 textmetadata
```

And the s3rver server output: 

```bash
./bin/s3rver.js -d /tmp/s3rver_test_directory
now listening on host localhost and port 4568
info: [S3rver] Fetched 6 buckets
info: [S3rver] GET / 200 933 - 5.581 ms
info: [S3rver] Fetched bucket "bucket1" with options %s marker=null, prefix=null, maxKeys=1000, delimiter=null
info: [S3rver] Found 5 objects for bucket "bucket1"
info: [S3rver] GET /bucket1?prefix=&encoding-type=url 200 1775 - 7.305 ms
```

Which version of s3rver are you using?

**Comment by jamhall** [comment]
I've just pushed a new release onto NPM. Perhaps the recent pull contributions have solved this problem. Please update and let me know. Thank you!

**Comment by justinmchase** [comment]
No dice. I am on a mac, is that possibly the difference here? I ran it from the commandline this time like you had in your example above.

What is your directory file structure? Do you have any metadata files in the directory that you need to create in order to enable this?

**Comment by justinmchase** [comment]
So I just created some files on my local file system but after stepping through the code it looks like in order to get files in here in the right way I should PUT them in through the server instead?

**Comment by jamhall** [comment]
I don't think would be much difference between Linux and Mac (I will try it on my mac)

Here is a list of the contents of a bucket (/tmp/s3rver_test_directory/bucket6):

```bash
tree  -a bucket6
bucket6
└── folder1
    ├── file1.txt
    │   ├── .dummys3_content
    │   └── .dummys3_metadata
    ├── file2.txt
    │   ├── .dummys3_content
    │   └── .dummys3_metadata
    ├── folder2
    │   ├── file3.txt
    │   │   ├── .dummys3_content
    │   │   └── .dummys3_metadata
    │   ├── file4.txt
    │   │   ├── .dummys3_content
    │   │   └── .dummys3_metadata
    │   ├── file5.txt
    │   │   ├── .dummys3_content
    │   │   └── .dummys3_metadata
    │   └── file6.txt
    │       ├── .dummys3_content
    │       └── .dummys3_metadata
    ├── folder3
    │   └── file10.txt
    │       ├── .dummys3_content
    │       └── .dummys3_metadata
    └── folder4
        ├── file7.txt
        │   ├── .dummys3_content
        │   └── .dummys3_metadata
        ├── file8.txt
        │   ├── .dummys3_content
        │   └── .dummys3_metadata
        └── folder5
            └── file9.txt
                ├── .dummys3_content
                └── .dummys3_metadata

15 directories, 20 files
```

If your bucket has objects, then yours look similar to this.

**Comment by jamhall** [comment]
Yes, the files must be created through the server because we associate a metadata file to each object.

**Comment by jamhall** [comment]
An object is actually a folder and we store the content in a separate file and the metadata in another file. 
For example, this is the metadata for an object:

```json
{
  "md5": "eb540c2d33cfb7daadc96822b82ca3c9",
  "contentType": "application/octet-stream",
  "size": 52359,
  "modifiedDate": "2017-02-22T16:07:52.002Z",
  "creationDate": "2017-02-22T16:07:52.002Z",
  "customMetaData": [
    {
      "key": "x-amz-meta-somekey",
      "value": "value"
    }
  ]
}
```

Custom properties can also be associated to an object. In this case: x-amz-meta-somekey.

**Comment by justinmchase** [comment]
GOT IT!

Ok so it wasn't clear to me, and I think I can work with this no problem but I would say that it would be a feature request maybe to treat plain old files as objects and dynamically generate that metadata would be pretty useful.

Thank you for walking me through it.
