### ISSUE TITLE
Add the possibility to disable the vhost resolution

### ISSUE THREAD

**Issue by ksnll** [jamhall/s3rver#557]
In our organisation current testing setup, we don't use `localhost` to access local services but we use another hostname such as `local.organisation`

In newer version of s3rver, using this hostname to access a bucket, will force a resolution to a specific bucket `local.organisation:port/local.organisation`.

For this reason, we cannot update s3rver to a newer version 😢 

It would be nice to have the option to disable the vhost resolution through an option. 
I gave it a go in creating a PR for this

**Comment by allan-simon** [comment]
we have the same problem, we s3rver in our CI, where we can give it one and only one docker alias , which make  bucket name vhost resolution impossible , instead we've always been using the "bucket name in the path" method 

and as the author, that has forced us to some woraround , we instead use the ip adress directly (which may be useful for you @ksnll  )

**Comment by kherock** [comment]
@ksnll This is definitely valid, and I'm planning for a relatively simple workaround in the next minor release where both `os.hostname()` and the custom service endpoint will resolve to the S3 service root. So both of the following should work once it's implemented:

On an OS with hostname `localhost.organisation`, just running
```console
$ s3rver -d ./data
```
would have s3rver resolve the path to `my-bucket` in `http://local.organisation/my-bucket`.

Alternatively, an OS with hostname `s3.localhost.organisation` you could run
```console
$ s3rver -d ./data --service-endpoint local.organisation
```
and s3rver would resolve `my-bucket` for `http://s3.local.organisation/my-bucket/`.

**Comment by eliasdorneles** [comment]
@kherock and what are your thoughts on the solution implemented at: https://github.com/jamhall/s3rver/pull/558 (basically, adding a feature flag) ?

**Comment by kherock** [comment]
I'm still debating what the best behavior will be going forward since path-style access will be slowly disappearing and it's something I want to have addressed for v4. I think regardless people are going to want a way to continue support for path style-access so I'm supportive of something like a `--no-vhost` option.

**Comment by eliasdorneles** [comment]
Yeah, that would be really cool indeed!

And considering it doesn't seem to cost much (since it's already implemented for `localhost` and access with IP address), I see no downsides. :)

**Comment by eliasdorneles** [comment]
That's awesome, thank you!
