### ISSUE TITLE
Cleaning up the directory after s3rver.close()

### ISSUE THREAD

**Issue by Junkern** [jamhall/s3rver#58]
I am using s3rver in my mocha tests, it's great so far!

I have one recommendation, though:
When calling `s3Instance.close()`, the directory passed to the constructor should be cleaned up and emptied. It's more convenient that way;)

**Comment by Junkern** [comment]
I agree with you that it should not be default (that would probably break stuff for some users).

What about  `s3Instance.close(options?: Options)`? At the moment the optional `options` parameter would contain a `cleanup: boolean` flag?

**Comment by n1ru4l** [comment]
The first param of `s3Instance.close`is currently a callback. We would have to add it as a second param?

Yes! We can split this into two tasks. Lets first implement the the `cleanup` option and later the cli option.

@leontastic Are you okay with this?

**Comment by leontastic** [comment]
Could we add it as an option on initialization? Would be better than tacking options _after_ a done callback IMO.

```javascript
new S3rver({
  hostname: FAKE_S3_HOSTNAME,
  port: FAKE_S3_PORT,
  // ...
  removeBucketsOnClose: true
})
```

Don't really care what it's named as long as it's clear and documented.

**Comment by Junkern** [comment]
Option on initialization is even better. I can also volunteer to provide a PR, in case you guys haven't started yet. Might take until next week, though.

**Comment by leontastic** [comment]
@Junkern Any contributions you make would be hugely appreciated!

**Comment by n1ru4l** [comment]
I need this feature so I started creating failing tests in #98

**Comment by Junkern** [comment]
Awesome, thank you!
