### ISSUE TITLE
CORS not working

### ISSUE THREAD

**Issue by sebolio** [jamhall/s3rver#594]
Hello. I just tried s3rver from terminal using curl and it works perfect, but when I try to use it in real world (a VueJS app) it ends up in tragedy.

I copied and pasted my CORS settings from S3, which work just fine from VueJS, and I see only errors before me.

CORS:
```xml
<CORSConfiguration>
<CORSRule>
    <AllowedOrigin>http://localhost:8080</AllowedOrigin>
    <AllowedMethod>POST</AllowedMethod>
    <AllowedMethod>GET</AllowedMethod>
    <AllowedMethod>PUT</AllowedMethod>
    <AllowedMethod>DELETE</AllowedMethod>
    <AllowedMethod>HEAD</AllowedMethod>
</CORSRule>
</CORSConfiguration>
```

El error:

> Access to XMLHttpRequest at 'http://localhost:9999/sitio/image.jpg' from origin 'http://localhost:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

The script:

```js
const S3rver = require('s3rver');
const fs = require('fs');

const corsConfig = require.resolve('./cors.xml');
const websiteConfig = require.resolve('s3rver/example/website.xml');

new S3rver({
  configureBuckets: [
    {
      name: 'sitio',
      configs: [fs.readFileSync(corsConfig), fs.readFileSync(websiteConfig)],
    },
  ],
  port: 9999,
  hostname: 'localhost',
  silent: false,
  directory: '/tmp/s3rver_test_directory',
}).run((err, { address, port } = {}) => {
  if (err) {
    console.error(err);
  } else {
    console.log('* S3RVER %s : %d', address, port);
  }
});
```

**Comment by JunaidUK** [comment]
Try adding `<AllowedHeader>*</AllowedHeader>` to your `cors.xml`. Otherwise the preflight check (the `OPTIONS` HTTP request) won't pass. https://github.com/jamhall/s3rver/issues/346 is another example of this.

**Comment by sebolio** [comment]
@JunaidUK thanks for your help, but when I follow your suggestion I get an error about wildcards not permitted:

```
Access to XMLHttpRequest at 'http://localhost:9999/garetto/5f35780b-IMG_0378.JPG' from origin 'http://localhost:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.
```

**Comment by webpepper** [comment]
Same problem here. Tried everything configuration-wise without success.

Perhaps the bug is in the [cors middleware](https://github.com/jamhall/s3rver/blob/master/lib/middleware/cors.js)? 

Inserting `return;` right after [this line](https://github.com/jamhall/s3rver/blob/b8355f90f46a9c0ea321796f8a73af82f0a65c56/lib/middleware/cors.js#L79) fixes it.

Since we're already checking if it's a preflight request and processing it, why continue after setting all the CORS headers? I.e., calling `next()` to continue downstream makes no sense.

**Comment by sebolio** [comment]
I finally fixed. It's been a long while since I posted this issue but I fixed it by specifying each domain manually.
