### ISSUE TITLE
Problem with index and error documents when Dockerizing 

### ISSUE THREAD

**Issue by tforster** [jamhall/s3rver#68]
I am trying to wrap s3rver in a Docker container so that it can be easily run standalone. A number of other people have done this as evidenced by all the different Github and DockerHub repos available. However, nobody seems to be supporting --indexDocument and --errorDocument. When I include those params in my builds s3rver still starts but all GET calls simply return:

```xml
<Error>
<Code>NoSuchBucket</Code>
<Message>The specified bucket does not exist</Message>
<Resource>192.168.99.100</Resource>
<RequestId>1</RequestId>
</Error>
```

If I remove those params from my ENTRYPOINT and leave --hostname, --port and --directory everything works as expected.

s3rver is a great tool especially for prototyping S3 hosted SPA apps where the index and error docs provide the infrastructure for routing. I would be happy to submit a pull request for a working Dockerfile if I can figure out how to get i and -e params working.

**Comment by leontastic** [comment]
Based on a cursory skim through the code, I believe we support (and have tests for) this feature now. Please open a new issue if this isn't working for you.
