### ISSUE TITLE
vhostBuckets Documentation Confusing

### ISSUE THREAD

**Issue by fishcharlie** [jamhall/s3rver#685]
In the README it says the `vhostBuckets` property means `Disable vhost-style access for all buckets`.

The description makes it sound like if this property is set to `true` that it will disable vhost-style access for all buckets. However, when reading the code `vhostBuckets: true` that makes it sound like it will enable vhost style access.

Which is it?

**Comment by kherock** [comment]
Yeah, in this case the description for the cli option `--no-vhost-buckets` probably shouldn't have been reused for the JS API. It should be `Allow vhost-style access for all buckets` here.

**Comment by fishcharlie** [comment]
@kherock Put up a PR to fix this: #687
