### ISSUE TITLE
Storage Class not being respected

### ISSUE THREAD

**Issue by Jake7D** [jamhall/s3rver#727]
Hi,

We're running a dockerised version of S3rver alongside our application for testing. We're trying to test that the storage class is being set correctly, but it always seems to be being set to STANDARD, instead of the supplied STANDARD_IA.

We've tried running it from the aws cli too and get the same issue. 

Here's the command we're running for the put-object:
`AWS_SECRET_ACCESS_KEY=S3RVER AWS_ACCESS_KEY_ID=S3RVER aws --no-verify-ssl --endpoint-url https://s3rver-ip s3api put-object --bucket test-bucket --key blah --storage-class STANDARD_IA`

And the response we get back from listing the bucket:
`{
            "Key": "blah",
            "LastModified": "2021-05-05T15:08:52+00:00",
            "ETag": "\"d41d8cd98f00b204e9800998ecf8428f\"",
            "Size": 0,
            "StorageClass": "STANDARD"
}`

Is this feature not supported?

**Comment by kherock** [comment]
No, we don't currently store any info pertaining to a storage class, though I think it should be easy to support the behavior of the other standard storage classes. It should be as simple as adding `x-amz-storage-class` to the allowed metadata here:
 https://github.com/jamhall/s3rver/blob/54825112d0621d468b383139dd947b113a1bf101/lib/models/object.js#L35-L43

**Comment by Jake7D** [comment]
Sounds great, is this likely to make it into a new version soon?

**Comment by kherock** [comment]
I should be able to cut a new 3.x release soon with a fix for this since it's pretty simple. I'll close this issue when that happens!

**Comment by kherock** [comment]
I've given this some initial support in v3.7.0 which should be available on npm!

**Comment by Jake7D** [comment]
great stuff, we'll give it a go!
