### ISSUE TITLE
Setup renovate to automatically bump package versions

### ISSUE THREAD

**Issue by n1ru4l** [jamhall/s3rver#80]
This allows easier dependency upgrades. (https://renovateapp.com/)
At the moment many dependencies are outdated. (https://david-dm.org/jamhall/s3rver)

If you are fine with it I can create a Pull Request for it once #79 is merged.

**Comment by leontastic** [comment]
@n1ru4l Thank you for #79. Sounds good, I've never used renovate so would appreciate your contribution!

**Comment by n1ru4l** [comment]
Someone will have to add the integration (https://github.com/settings/installations/71087).

Idk if you can do it, otherwise @jamhall will have to do it. 

Once activated renovate will create a PR with the initial configuration (which I can adjust).

**Comment by leontastic** [comment]
@jamhall will need to do it as he is the repository owner. Seems like Renovate can only be added by the repository owner, either user or organization.

**Comment by jamhall** [comment]
@leontastic  @n1ru4l  - Hello! I have added the renovate integration to the project. Let me know me if I have to do anything else.

**Comment by n1ru4l** [comment]
@jamhall Awesome thank you ☺️

**Comment by jamhall** [comment]
@n1ru4l @leontastic  - Renovate has opened a pull request for adding the renovate.json file. Ok to merge?

**Comment by n1ru4l** [comment]
Not yet I will customize the configuration first

**Comment by n1ru4l** [comment]
We can now merge #83 and afterwards #82.

If you want you can also add me as a collaborator, will contribute some more stuff in the near future like support for presigned urls.

**Comment by leontastic** [comment]
@jamhall Is the only one with the power to invite collaborators. The more the merrier IMO

**Comment by jamhall** [comment]
@n1ru4l  - You should have received an invite :-) Integration of presigned URLs would be awesome. Cheers!
